spring.application.name=demo

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campus_fests?serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ORM
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Jackson
spring.jackson.time-zone=Asia/Kolkata

# Web
server.error.include-message=always

# JWT
app.jwt.secret=change-me-change-me-change-me-change-me
app.jwt.expiration-ms=86400000

spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true

